image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - mai # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-card-delivery.jar &

build_script:
  - chmod +x gradlew  # добавляем права на запуск файла gradlew
  - ./gradlew test --info -Dselenide.headless=true